[package]
name = "auth"
version = "0.1.0"
authors = ["Henry <henry@coolbet.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
r2d2 = "0.8"
r2d2_postgres = "0.18"
# config="0.11"